# Generated by Django 6.0.5 on 2026-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_checkout_request_id_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mpesa_receipt',
        ),
    ]
